name : feature-release
run-name: ${{ github.actor }} is releasing new feature
on :
  push :
    tags:
      - v*.*.*

jobs :
  ci-tag:
    runs-on : ubuntu-latest
    env : 
      TAG_NAME : ${{ github.ref }}
    steps:
      - uses : actions/checkout@v3
        with:
          token : ${{ secrets.PUSH_MAIN }}
      - uses : actions/setup-node@v3
        with : 
          node-version : 16
          cache : 'yarn'
      - name : Set env var
        run : echo "${{ github.ref }}"
      - name : config user git
        run : |
          git config --global user.email "${{ github.event.pusher.email }}"
          git config --global user.name "${{ github.actor }}"
      - run : npm install -g yarn
      - run : yarn --frozen-lockfile
      - name : build
        run : yarn build
      - name : test
        run : yarn lint && yarn test:ci
      - name : Merge feature to main
        run : |
          git fetch --unshallow
          git checkout main
          git merge ${{ env.TAG_NAME }}
          git push origin main
          git tag -a ${{ env.TAG_NAME }} -m "my version ${{ env.TAG_NAME }}"
          git push origin main --tags
          
  # ci-feature:
  #   runs-on : ubuntu-latest
  #   needs :
  #     - ci-tag
  #   steps:
  #     - uses : actions/checkout@v3
  #       with:
  #         token : ${{ github.token }}
  #     - uses : actions/setup-node@v3
  #       with : 
  #         node-version : 16
  #         cache : 'yarn'
  #     - name : config user git
  #       run : |
  #         git config --global user.email "${{ github.event.pusher.email }}"
  #         git config --global user.name "${{ github.actor }}"
  #     - name : Release to main
  #       uses : actions/create-release@v1
  #       env : 
  #         GITHUB_TOKEN : ${{ secrets.PUSH_MAIN }}
  #       with : 
  #         tag_name : ${{ github.ref }}
  #         release_name : release ${{ github.ref }}
  #         draft : false
  #         prerelease  : false