name : main-release
run-name: ${{ github.actor }} is releasing new main
on :
  push :
    tags:
      - v*.*.*

jobs :
  ci-feature:
    runs-on : ubuntu-latest
    steps:
      - uses : actions/checkout@v3
        with:
          token : ${{ github.token }}
      - uses : actions/setup-node@v3
        with : 
          node-version : 16
          cache : 'yarn'
      - name : config user git
        run : |
          git config --global user.email "${{ github.event.pusher.email }}"
          git config --global user.name "${{ github.actor }}"
      - name : Release to main
        uses : actions/create-release@v1
        env : 
          GITHUB_TOKEN : ${{ github.token }}
        with : 
          tag_name : ${{ github.ref }}
          release_name : release ${{ github.ref }}
          draft : false
          prerelease  : false